# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Web interaction and animation'
tagline:          'A learning showcase'
description:      'A Sample blog using Jekyll Metro'
url:              'http://plumpnation.github.io/interactive-animation/'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: about/
- text: Blog
  url: blog/
- text: Tags
  url: tags/
- text: Archive
  url : archive/

# Author Details
author:         'Gavin King'
linkedin:       'https://www.linkedin.com/in/plumpnation/'
twitter:        'https://twitter.com/plumpnation'
facebook:       'https://www.facebook.com/plumpnation'
gplus:          'https://plus.google.com/u/1/+GavinKing_AKA_plumpNation/posts'

# Google Analytics
gahandler:

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: plumpnation@gmail.com
  facebook: plumpnation
  flickr:
  github: plumpnation
  instagram:
  linkedin: plumpnation
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: plumpnation
  twitter: plumpnation
  stackoverflow: http://stackoverflow.com/users/1888094/plumpnation

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.0.1
